### ISSUE TITLE
Fenix 3 compatible?

### ISSUE THREAD

**Issue by MarsNielson** [gatkin/commute-tracker#2]
Hi there,

Would it be possible to make this great app Fenix 3 compatible?
Thanks in advance

**Comment by Flip7** [comment]
Yes - I read about this app in an online review and was bummed that it doesn't support fenix 3.
Could you please make it compatible for fenix 3?
If you access donations, I would make one.

**Comment by gatkin** [comment]
Yes, I will work on updating this app to add fenix 3 compatibility. It should hopefully just be an issue of making the layouts fit on the round face of the fenix.

**Comment by MarsNielson** [comment]
Awesome!
Looking very much forward to it.

**Comment by gatkin** [comment]
The new version is in the Connect IQ store. I do not have access to an actual fenix3 device for testing, so please let me know if you notice any issues with the app on the fenix3.

**Comment by MarsNielson** [comment]
Downloaded it and tried it this morning. It works flawlessly.

But, is there any way to change the miles to kilometers and the 12:00h watch to 24:00h watch?

**Comment by gatkin** [comment]
Great! And yes there should be a way to do this.I have created issue #4 for this
